#!/usr/bin/env python3
"""Generate SAFE-2026-09.md and CONFLICTS.md from SAFE-2026-09.yaml. pyyaml only."""
import sys, pathlib, yaml

HERE = pathlib.Path(__file__).resolve().parent
SRC = HERE / "SAFE-2026-09.yaml"
REQUIRED = ["id", "value", "unit", "statement", "basis", "confidence", "source",
            "as_of", "status", "printed_in", "notes"]
BASES = {"internal", "published", "derived", "triangulated", "estimated",
         "asserted-internal", "unverified"}
STATUSES = {"canonical", "superseded", "retired", "open"}
CONFS = {"H", "M", "L"}


def cell(v):
    if v is None:
        return ""
    if isinstance(v, (list, tuple)):
        return ", ".join(cell(x) for x in v)
    return " ".join(str(v).split()).replace("|", "\\|")


def validate(doc):
    errs, ids = [], {}
    groups = set(doc["meta"]["groups"])
    for f in doc["facts"]:
        fid = f.get("id", "<no id>")
        for k in REQUIRED:
            if k not in f:
                errs.append(f"{fid}: missing {k}")
        if fid in ids:
            errs.append(f"{fid}: duplicate id")
        ids[fid] = f
        if fid.split(".")[0] not in groups:
            errs.append(f"{fid}: group not in meta.groups")
        if f.get("basis") not in BASES:
            errs.append(f"{fid}: bad basis {f.get('basis')!r}")
        if f.get("status") not in STATUSES:
            errs.append(f"{fid}: bad status {f.get('status')!r}")
        if f.get("confidence") not in CONFS:
            errs.append(f"{fid}: bad confidence {f.get('confidence')!r}")
        if f.get("status") == "open" and f.get("value") is not None and not f.get("notes"):
            errs.append(f"{fid}: open with a value needs notes")
    for f in doc["facts"]:
        for c in f.get("conflicts_with") or []:
            if c not in ids:
                errs.append(f"{f['id']}: conflicts_with unknown id {c}")
    return errs, ids


def clusters(facts):
    """Connected components over conflicts_with (union-find)."""
    parent = {}

    def find(x):
        while parent.setdefault(x, x) != x:
            x = parent[x]
        return x

    for f in facts:
        for c in f.get("conflicts_with") or []:
            parent[find(f["id"])] = find(c)
    comps = {}
    for f in facts:
        if f.get("conflicts_with") or f.get("conflict_topic"):
            comps.setdefault(find(f["id"]), []).append(f)
    return list(comps.values())


def write_sheet(doc, ids):
    m = doc["meta"]
    out = [f"# InventWood investor data - {m['round']} {m['round_period']}", "",
           f"As of **{m['as_of']}**. GENERATED from `SAFE-2026-09.yaml` by `build.py` - "
           "the YAML is the authority; do not edit this file.", "",
           "Columns: Fact (`id` - statement) | Value | Basis | Conf | Source | Printed in | Status. "
           "`OPEN` = value not decided; `CONFLICT` = see [CONFLICTS.md](CONFLICTS.md); "
           "superseded/retired rows are kept for traceability and must not be printed.", ""]
    n = len(doc["facts"])
    n_open = sum(f["status"] == "open" for f in doc["facts"])
    n_conf = sum(bool(f.get("conflicts_with")) for f in doc["facts"])
    out += [f"{n} facts, {n_open} open, {n_conf} in conflict clusters.", ""]
    for g in m["groups"]:
        rows = [f for f in doc["facts"] if f["id"].split(".")[0] == g]
        if not rows:
            continue
        out += [f"## {g}", "", "| Fact | Value | Basis | Conf | Source | Printed in | Status |",
                "|---|---|---|---|---|---|---|"]
        for f in rows:
            st = f["status"].upper() if f["status"] != "canonical" else "canonical"
            if f.get("conflicts_with"):
                st += " CONFLICT"
            src = cell(f["source"])
            for k in ("url", "url2", "url3"):
                if f.get(k):
                    src += f" <{f[k]}>"
            conf = cell(f["confidence"])
            if f.get("confidence_label"):
                conf += f" ({cell(f['confidence_label'])})"
            unit = f" {cell(f['unit'])}" if f.get("unit") else ""
            val = cell(f["value"]) if f["value"] is not None else "*null*"
            out.append(f"| `{f['id']}` - {cell(f['statement'])} | {val}{unit} | {cell(f['basis'])} | "
                       f"{conf} | {src} | {cell(f['printed_in']) or '-'} | {st} |")
        out.append("")
    (HERE / "SAFE-2026-09.md").write_text("\n".join(out))


def write_conflicts(doc, ids):
    out = [f"# Conflicts and open decisions - as of {doc['meta']['as_of']}", "",
           "GENERATED from `SAFE-2026-09.yaml` by `build.py`. Every cluster of facts linked by "
           "`conflicts_with`, then every `status: open` fact. A `Decision:` line is filled from the "
           "YAML `decision` / `decided_by` fields; otherwise it reads `OPEN - Alex`.", ""]
    cl = clusters(doc["facts"])
    out += [f"## Conflicts ({len(cl)} clusters)", ""]
    for i, comp in enumerate(sorted(cl, key=lambda c: c[0]["id"]), 1):
        topic = next((f["conflict_topic"] for f in comp if f.get("conflict_topic")), comp[0]["statement"])
        out += [f"### C{i}. {topic}", ""]
        for f in sorted(comp, key=lambda f: (f["status"] != "canonical", f["id"])):
            unit = f" {cell(f['unit'])}" if f.get("unit") else ""
            val = cell(f["value"]) if f["value"] is not None else "*null*"
            out.append(f"- `{f['id']}` [{f['status']}, {cell(f['basis'])}, {f['confidence']}] "
                       f"**{val}**{unit} - {cell(f['statement'])}; printed in: {cell(f['printed_in']) or '-'}")
            if f.get("notes"):
                out.append(f"  - {cell(f['notes'])}")
        dec = next((f["decision"] for f in comp if f.get("decision")), None) \
            or next((f["decided_by"] for f in comp if f.get("decided_by")), None)
        out += ["", f"**Decision:** {cell(dec) if dec else 'OPEN - Alex'}", ""]
    opens = [f for f in doc["facts"] if f["status"] == "open"]
    out += [f"## Open facts ({len(opens)})", ""]
    for f in opens:
        val = cell(f["value"]) if f["value"] is not None else "*null*"
        out.append(f"- `{f['id']}` - {cell(f['statement'])}. Candidate value: {val}. {cell(f['notes'])}")
        out.append(f"  - **Decision:** {cell(f['decision']) if f.get('decision') else 'OPEN - Alex'}")
    out.append("")
    (HERE / "CONFLICTS.md").write_text("\n".join(out))


def main():
    doc = yaml.safe_load(SRC.read_text())
    errs, ids = validate(doc)
    if errs:
        print("\n".join(errs), file=sys.stderr)
        sys.exit(1)
    write_sheet(doc, ids)
    write_conflicts(doc, ids)
    n_open = sum(f["status"] == "open" for f in doc["facts"])
    print(f"{len(doc['facts'])} facts, {n_open} open, {len(clusters(doc['facts']))} conflict clusters -> "
          "SAFE-2026-09.md, CONFLICTS.md")


if __name__ == "__main__":
    main()
